### ISSUE TITLE
Venue

### ISSUE THREAD

**Issue by daviddias** [daviddias/snow.js#1]
Let's make this happen! :D The first two questions that we have to answer is `where` and `when`? February might be a good shot, if everyone is available of course. I never did snowboard/ski, so if someone has some good recommendations, it would be great!

**Comment by achingbrain** [comment]
If you're a beginner, March might be a better bet as it'll be a bit warmer - the snow will be softer and the weather will be more conducive to beers on the terrace at the end of the day, etc.

I'm partial to the Portes du Soleil so would recommend Morzine as a resort.  It's a small town not a ski village so it's nice to hang out in - there are good shops/bars/restaurants and it has access to 650km of runs and some pretty epic back/slack country.

@alanshaw, @olizilla and I have stayed with [Mountain Utopia](http://mountainutopia.co.uk) a few times.  It's a small independent company with two chalets across the road from each other.  Toby & Tamara are really great, amazingly helpful, drive you everywhere and the food is just awesome.  Airport transfers, hot tub, sauna, underfloor heating, log fires, free beer/wine with dinner, Sunday changeovers to minimise queuing in Geneva Airport; all the good stuff.

We've also had super fun times with [The Rider Social](http://www.theridersocial.com/) (based in Chatel, next valley over), but their thing is guiding/hiking/split boarding so it might be a bit advanced.  Maybe next year.
