### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by daviddias** [daviddias/snow.js#4]
So, keeping this ideia moving forward, we have to find the best possible time to make it happen :)

I know that @achingbrain has queried our Venue (so far) for availability and the returned value was 1st or 2nd week of March (1st Week of March might also be great, because @evilpacket is coming to Portugal on the last week of February, he might be able to join us! :D 

Nevertheless, I would like to know all your availability first and it this works for you after all

Let's say that a good place to shoot would be from the 3rd week of Feb, till the 3rd of March

|  | 15th Feb | 22nd Feb | 1st Mar | 8th Mar | 15th Mar | 22nd Mar |
| --- | --- | --- | --- | --- | --- | --- |
| David | ✔ | ✘ | ✘ | ✘ | ✔ | ✔ |
| Alex | ✘ | ✘ | ✔ | ✔ | ✘ | ✘ |

**Comment by achingbrain** [comment]
I changed the dates to be the week-starting Sunday because the weeks don't align very well in the calendar...

|  | 15th Feb | 22nd Feb | 1st Mar | 8th Mar | 15th Mar | 22nd Mar |
| --- | --- | --- | --- | --- | --- | --- |
| Alex | ✘ | ✘ | ✔ | ✔ | ✘ | ✘ |

**Comment by alanshaw** [comment]
I would really love to do this but just can't this year :(
